### ISSUE TITLE
Use looper prepare

### ISSUE THREAD

**Issue by asperon** [asperon/smoothcalendar#31]
USER_COMMENT=When I tried to change the default calendar app, it crashed
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=1.4.1
BRAND=docomo
PHONE_MODEL=SO-01G
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.preference.ListPreference.<init>(ListPreference.java:51)
at android.preference.ListPreference.<init>(ListPreference.java:72)
at se.catharsis.android.calendar.ConfigureActivity$UpdateApplicationList.doInBackground(ConfigureActivity.java:1123)
at se.catharsis.android.calendar.ConfigureActivity$UpdateApplicationList.doInBackground(ConfigureActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.preference.ListPreference.<init>(ListPreference.java:51)
at android.preference.ListPreference.<init>(ListPreference.java:72)
at se.catharsis.android.calendar.ConfigureActivity$UpdateApplicationList.doInBackground(ConfigureActivity.java:1123)
at se.catharsis.android.calendar.ConfigureActivity$UpdateApplicationList.doInBackground(ConfigureActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by asperon** [comment]
fixed in 1.5.1
